version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    networks:
      - minio-sample

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    ports:
      - "9092:9092"
      - "29092:29092"
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # ✅ fix
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1             # ✅ fix
    volumes:
      - /kafka-data:/var/lib/kafka
    networks:
      - minio-sample

  debezium:
    image: debezium/connect:3.0.0.Final
    ports:
      - "8083:8083"
      - "5005:5005"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_config
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
      CONNECT_TOPIC_CREATION_ENABLE: "true"
    depends_on:
      - kafka
    networks:
      - minio-sample

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: "-Xms32M -Xmx128M"
    depends_on:
      - kafka
    networks:
      - minio-sample

  simonevconsume_user:
    image: adamilkom00/simonevconsume_user:0.0.2
    container_name: simonevconsume_user
    restart: unless-stopped
    environment:
      - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
      - BROKERS=kafka:29092
      - GROUP_ID=user_consumeto_simonev
      - TOPIC=simak1.unpak_simak.user
      - TABLE=user_simak
    networks:
      - minio-sample

  simonevconsume_m_fakultas:
    image: adamilkom00/simonevconsume_m_fakultas:0.0.1
    container_name: simonevconsume_m_fakultas
    restart: unless-stopped
    environment:
      - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
      - BROKERS=kafka:29092
      - GROUP_ID=m_fakultas_consumeto_simonev
      - TOPIC=simak2.unpak_simak.m_fakultas
      - TABLE=m_fakultas_simak
    networks:
      - minio-sample

  simonevconsume_r_prodi:
    image: adamilkom00/simonevconsume_r_prodi:0.0.1
    container_name: simonevconsume_r_prodi
    restart: unless-stopped
    environment:
      - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
      - BROKERS=kafka:29092
      - GROUP_ID=r_prodi_consumeto_simonev
      - TOPIC=simak3.unpak_simak.r_prodi
      - TABLE=r_prodi_simak
    networks:
      - minio-sample

  simonevconsume_m_program_studi:
    image: adamilkom00/simonevconsume_m_program_studi:0.0.2
    container_name: simonevconsume_m_program_studi
    restart: unless-stopped
    environment:
      - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
      - BROKERS=kafka:29092
      - GROUP_ID=m_program_studi_consumeto_simonev
      - TOPIC=simak4.unpak_simak.m_program_studi
      - TABLE=m_program_studi_simak
    networks:
      - minio-sample

  # simonevconsume_pengguna:
  #   build:
  #     context: ./SimonevConsume_pengguna
  #     dockerfile: Dockerfile
  #   container_name: simonevconsume_pengguna
  #   restart: unless-stopped
  #   environment:
  #     - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
  #     - BROKERS=kafka:29092
  #     - GROUP_ID="pengguna_consumeto_simonev"
  #     - TOPIC="simpeg7.unpak_simpeg.pengguna"
  #     - TABLE="pengguna_simpeg"
  #   networks:
  #     - minio-sample

  # simonevconsume_e_pribadi:
  #   build:
  #     context: ./SimonevConsume_e_pribadi
  #     dockerfile: Dockerfile
  #   container_name: simonevconsume_e_pribadi
  #   restart: unless-stopped
  #   environment:
  #     - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
  #     - BROKERS=kafka:29092
  #     - GROUP_ID="e_pribadi_consumeto_simonev"
  #     - TOPIC="simpeg8.unpak_simpeg.e_pribadi"
  #     - TABLE="e_pribadi_simpeg"
  #   networks:
  #     - minio-sample

  # simonevconsume_n_pribadi:
  #   build:
  #     context: ./SimonevConsume_n_pribadi
  #     dockerfile: Dockerfile
  #   container_name: simonevconsume_n_pribadi
  #   restart: unless-stopped
  #   environment:
  #     - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
  #     - BROKERS=kafka:29092
  #     - GROUP_ID="n_pribadi_consumeto_simonev"
  #     - TOPIC="simpeg9.unpak_simpeg.n_pribadi"
  #     - TABLE="n_pribadi_simpeg"
  #   networks:
  #     - minio-sample

  # simonevconsume_n_pengangkatan:
  #   build:
  #     context: ./SimonevConsume_n_pengangkatan
  #     dockerfile: Dockerfile
  #   container_name: simonevconsume_n_pengangkatan
  #   restart: unless-stopped
  #   environment:
  #     - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
  #     - BROKERS=kafka:29092
  #     - GROUP_ID="n_pengangkatan_consumeto_simonev"
  #     - TOPIC="simpeg10.unpak_simpeg.n_pengangkatan"
  #     - TABLE="n_pengangkatan_simpeg"
  #   networks:
  #     - minio-sample

  # environment:
  #     - DSN=cdc:unp@kcdc0k3@tcp(172.16.20.245:3306)/unpak_simonev?parseTime=true
  #     - BROKERS=kafka:29092
  #     - GROUP_ID="payroll_m_pegawai_consumeto_simonev"
  #     - TOPIC="simpeg11.unpak_simpeg.payroll_m_pegawai"
  #     - TABLE="payroll_m_pegawai_simpeg"
  #   networks:
  #     - minio-sample

volumes:
  zookeeper-data:
  kafka-data:

networks:
  minio-sample:
    driver: bridge